{% set name = "jupyterlab-git" %}
{% set version = "0.51.1" %}
{% set sha256 = "b7bce89795d5ce88c8aaf0d79eb7a93d0535622f9be6b019ca9ae4d3b9a9ca6a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterlab_git/jupyterlab_git-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version
    - hatchling >=1.5.0
    - jupyterlab =4
    - pip
    - python {{ python_min }}
  run:
    - jupyter_server >=2.0,<3.0
    - python >={{ python_min }},<4.0
    - nbdime >=4.0,<5.0
    - nbformat
    - packaging
    - pexpect
    - traitlets >=5.0,<6.0
  run_constrained:
    - jupyterlab >=4,<5

test:
  requires:
    - jupyterlab
    - pip
    - python {{ python_min }}
  imports:
    - jupyterlab_git
  commands:
    - pip check
    - jupyter server extension list
    - jupyter server extension list 2>&1 | grep -ie "jupyterlab_git.*OK"
    - jupyter labextension list
    - jupyter labextension list 2>&1 | grep -ie "@jupyterlab/git.*OK.*(python, jupyterlab-git)"

about:
  home: https://github.com/jupyterlab/jupyterlab-git
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Git extension for JupyterLab
  description: A JupyterLab extension for version control using git
  dev_url: https://github.com/jupyterlab/jupyterlab-git

extra:
  recipe-maintainers:
    - krassowski
    - dlqqq
    - dbast
    - blink1073
    - fcollonval
