{% set name = "jupyterlab-git" %}
{% set version = "0.8.1" %}
{% set sha256 = "972611bf24120d9acd0261d7ea4cd6b5540fd5dd47c951b84cb60020e5d7d6d8" %}

package:
  name: {{ name|lower }}-server
  version: {{ version }}

source:
  url: https://github.com/jupyterlab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{PYTHON}} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - jupyterlab >=1.0.0
    - pip
    - python >=3.5
  run:
    - jupyterlab >=1.0.0
    - python >=3.5
    - nbdime >=1.1.0

test:
  imports:
    - jupyterlab_git

outputs:
  - name: {{ name|lower }}-server
    build:
      noarch: python

  - name: {{ name|lower }}
    build:
      noarch: python
    script: install-lab.bat  # [win]
    script: install-lab.sh  # [not win]
    requirements:
      build:
        - nodejs    
      host:
        - jupyterlab >=1.0.0
        - python >=3.5
      run:
        - python >=3.5
        - nodejs
        - {{ pin_subpackage('jupyterlab-git-server', exact=True) }}
    test:
      imports:
        - jupyterlab_git
      commands:
        - jupyter labextension list
        - jupyter lab build
  
  
about:
  home: https://github.com/jupyterlab/jupyterlab-git
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Git extension for JupyterLab
  description: A JupyterLab extension for version control using git
  dev_url: https://github.com/jupyterlab/jupyterlab-git

extra:
  recipe-maintainers:
    - dbast
    - blink1073
