{% set name = "jupyterlab-git" %}
{% set version = "0.50.0" %}
{% set sha256 = "09859546d390134ebb918a965c2c3fe2605feafe327cf61615be7dd90b5bdfbb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab_git/jupyterlab_git-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version
    - hatchling >=1.5.0
    - jupyterlab =3
    - pip
    - python >=3.6,<4.0
  run:
    - jupyter_server >=1.0,<3.0
    - jupyterlab <4.0
    - python >=3.6,<4.0
    - nbdime >=3.1,<4.0
    - nbformat
    - packaging
    - pexpect
    - traitlets >=5.0,<6.0

test:
  requires:
    - jupyterlab =3
    - pip
  imports:
    - jupyterlab_git
  commands:
    - pip check
    - jupyter server extension list
    - jupyter server extension list 2>&1 | grep -ie "jupyterlab_git.*OK"
    - jupyter labextension list
    - jupyter labextension list 2>&1 | grep -ie "@jupyterlab/git.*OK.*(python, jupyterlab-git)"

about:
  home: https://github.com/jupyterlab/jupyterlab-git
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Git extension for JupyterLab
  description: A JupyterLab extension for version control using git
  dev_url: https://github.com/jupyterlab/jupyterlab-git

extra:
  recipe-maintainers:
    - dbast
    - blink1073
    - fcollonval
